services:
  app:
    build:
      context: ./
      dockerfile: docker/app/app.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
  web:
    build:
      context: ./
      dockerfile: docker/web/web.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - app-network
#  tippit-frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "5173:5173" # Vite dev server
#    volumes:
#      - ./frontend:/app
#    working_dir: /app
#    command: ["pnpm", "dev", "--host"]
#    networks:
#      - app-network
#    depends_on:
#      - app
  database:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - app-network
  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - app-network
  pma:
    image: phpmyadmin:5.2.1
    ports:
      - "8088:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=${DB_PORT}
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
